version: '3'
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ./server/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=7
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_LOOP_LAPSE=1m2s
      - CLI_LOG_LEVEL=DEBUG
      - CLI_FIRSTNAME=Ivan
      - CLI_LASTNAME=Soriano
      - CLI_DOCUMENT=41824203
      - CLI_BIRTHDATE=1999-04-11

    networks:
      - testing_net
    depends_on:
      - server

  server-test:
    container_name: server-test
    build: ./server-test
    image: server-test
    entrypoint: python3 /test.py
    networks:
        - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
